### ISSUE TITLE
使用伪元素清除浮动

### ISSUE THREAD

**Issue by rxliuli** [rxliuli/fragment_knowledge#14]
相比于 [使用 `Overflow: hidden` 清除浮动](https://github.com/rxliuli/fragment_knowledge/issues/8)，这种方式显然更加**标准**一些。

HTML

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>使用伪元素清除浮动</title>
    <link rel="stylesheet" href="./css/common.css" />
    <link rel="stylesheet" href="./css/clear_pseudo_element.css" />
  </head>
  <body>
    <div class="clear_float box1">
      <ul>
        <li>文本内容 1</li>
        <li>文本内容 2</li>
        <li>文本内容 3</li>
      </ul>
    </div>
    <div class="clear_float box2">
      <ul>
        <li>文本内容 1</li>
        <li>文本内容 2</li>
        <li>文本内容 3</li>
      </ul>
    </div>
  </body>
</html>
```

CSS

```css
li {
  float: left;
}

.clear_float::before,
.clear_float::after {
  content: '';
  display: table;
}
.clear_float {
  clear: both;
}

.box1,
.box2 {
  margin: 100px;
}
```
