### ISSUE TITLE
浏览器默认样式重置

### ISSUE THREAD

**Issue by rxliuli** [rxliuli/fragment_knowledge#16]
```css
/* 清除内外边距 */
h1,
h2,
h3,
h4,
h5,
h6,
ul,
ol,
li,
dl,
dt,
dd,
p,
div,
main,
header,
section,
article,
footer {
  margin: 0;
  padding: 0;
}
/* 列表 */
ul,
ol,
dl {
  list-style-type: none;
}
```
