### ISSUE TITLE
继承与通用选择符

### ISSUE THREAD

**Issue by rxliuli** [rxliuli/fragment_knowledge#17]
之前说过尽量不要直接用通用选择符 `*` 清除内外边距，原因是 CSS 权重的问题。

- CSS 权重: `行内样式 > ID > 类/伪类/属性 > 类型/伪元素 > 通用 > 继承`
    - 注: 尽量降低权重以避免复杂度过高，简而言之就是: **class 是给 CSS 用的，id 是给 JS 用的。**
    - 注: 如果权重相等, 则后定义的会覆盖前面的

下面继承的样式就被通用选择符覆盖掉了

```css
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>继承和通用选择符</title>
    <style>
      /* h2 让子元素继承的属性会被通用选择符覆盖，毕竟继承的样式没人权.JPG（权重为负数 #笑） */
      * {
        color: black;
      }
      h2 {
        color: red;
      }
    </style>
  </head>
  <body>
    <h2>这是一个红色标题，但 <em>这里</em> 是黑色的</h2>
  </body>
</html>
```
