### ISSUE TITLE
使用伪元素的高级示例

### ISSUE THREAD

**Issue by rxliuli** [rxliuli/fragment_knowledge#18]
伪元素很有用，这里列出一个应用场景: **进行文字内容的排版**。

下面并没有使用多少 CSS 代码，但却实现了不错的文章排版。

```css
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>伪元素</title>
    <style>
      /* 添加装饰性大引号 */
      .chapter::before {
        float: left;
        content: '”';
        font-size: 15rem;
      }
      /* 首字下沉 */
      .chapter p::first-letter {
        float: left;
        font-size: 2rem;
      }
      /* 第一行加粗 */
      .chapter p::first-line {
        font-weight: bold;
      }
      /* 清除浮动的影响 */
      .chapter::after {
        content: ' ';
        display: table;
        clear: both;
      }
    </style>
  </head>
  <body>
    <article>
      <h1>JavaScript 实现更多数组的高阶函数</h1>
      <section class="chapter">
        <p>
          为什么有了 Lodash 这种通用函数工具库，吾辈要写这篇文章呢？吾辈在
          SegmentFault 上经常看到关于 JavaScript
          数组的相关疑问，甚至于，相同类型的问题，只是数据变化了一些，就直接提出了一个新的问题（实际上，对自身并无帮助）。简单搜索了一下
          Array，居然有 2360+ 条的结果，足可见这类问题的频率之高。若是有一篇适合
          JavaScript
          萌新阅读的自己实现数组更多操作的文章，情况或许会发生一些变化。
        </p>
      </section>
    </article>
    <p>其他内容</p>
  </body>
</html>
```

效果图

![image](https://user-images.githubusercontent.com/24560368/62615742-772d1700-b940-11e9-8ad2-18e58911140a.png)
