### ISSUE TITLE
全屏化元素

### ISSUE THREAD

**Issue by rxliuli** [rxliuli/fragment_knowledge#28]
如何全屏化元素呢？例如在宣传页、反广告屏蔽、图片全屏预览都需要该功能，我们该如何做呢？
事实上，使用绝对/固定定位可以轻易实现这个需求。

```css
.full,
.full-window {
  width: 100%;
  /*这里可以直接根据窗口高度设置百分比*/
  height: 100%;
}
/* 全屏 */
.full-window {
  position: fixed;
}
/* 充满最近的父级上下文容器 */
.full {
  position: absolute;
}
```

使用也很简单

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>固定定位全页面布局</title>
    <link rel="stylesheet" href="../common.css" />
    <style>
      /* 适用绝对定位占满全屏 */
      .home {
        background-image: url('https://via.placeholder.com/1920x1080');
        background-size: cover;
      }
    </style>
  </head>
  <body>
    <div class="full home"></div>
  </body>
</html>
```

恐怕你也注意到了，吾辈实现了两个 class，分别是 `full` 和 `full-window`。它们的主要区别是绝对定位会在存在定位上下文时充满最近的定位上下文而非整个窗口，当然我们放到 body 下面的话自然是充满整个窗口的。但是，`full-window` 则是在任何情况下都会充满当前窗口，因为它是相对于整个窗口的。前者主要用在元素悬浮浮层上面，后者则是用在全屏弹窗之类的。
