### ISSUE TITLE
CSS 的属性是有顺序的，后面的会覆盖前面的

### ISSUE THREAD

**Issue by rxliuli** [rxliuli/fragment_knowledge#7]
```css
div {
  padding-left: 10px;
  padding-right: 20px;
  padding:40px 50px 60px;
}
```

后面的 `padding` 大属性会覆盖掉前面的 `padding-left` 与 `padding-right`，之前一直以为是**小属性**覆盖**大属性**呢 #羞愧
