### ISSUE TITLE
Overflow: hidden 黑魔法可以清除浮动

### ISSUE THREAD

**Issue by rxliuli** [rxliuli/fragment_knowledge#8]
`Overflow: hidden` 属性的愿意是隐藏溢出的部分，但实际上却也可以用作清除浮动的**利器**，只要将之追加到浮动元素外层的盒子上。

HTML

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>使用 overflow:hidden 进行黑魔法</title>
  </head>
  <body>
    <div class="box1">
      <ul>
        <li>文本内容 1</li>
        <li>文本内容 2</li>
        <li>文本内容 3</li>
      </ul>
    </div>
    <div class="box2">
      <ul>
        <li>文本内容 1</li>
        <li>文本内容 2</li>
        <li>文本内容 3</li>
      </ul>
    </div>
  </body>
</html>
```

css

```css
li {
  float: left;
}
.box1,
.box2 {
  /* 使用这个黑魔法给父盒子加上就可以正常清除浮动并拥有正常的 margin 了（对比 clear_both） */
  overflow: hidden;
  margin: 100px;
}
```
